<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\KhodamTemplate;

class MoreKhodamSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            // SEREM
            ['Babi Ngepet Emas', 'Aura pesugihan level elit. Sekali gesek dapet Alphard, tapi minta tumbal pulsa.', 'hantu', '🐷', 98],
            ['Genderuwo Kos-kosan', 'Tinggi besar hitam berbulu. Suka jagain pintu kamar mandi kalau malam.', 'hantu', '👹', 85],
            ['Kuntilanak Ketawa', 'Tawanya melengking banget, tapi nangis kalau ditagih pinjol.', 'hantu', '👻', 82],
            ['Pocong Loncat', 'Lincah banget, sering juara satu lomba balap karung gaib.', 'hantu', '👻', 70],
            ['Tuyul Milenial', 'Bukan nyolong uang cash, tapi nyolong saldo OVO & GoPay.', 'hantu', '👶', 95],
            ['Suster Ngesot Salto', 'Level lanjutan dari ngesot, sekarang udah jago akrobat di lorong rumah sakit.', 'hantu', '🏥', 88],
            ['Buto Ijo Mabar', 'Badan gede sangar, tapi hobi main Mobile Legends di pos ronda.', 'hantu', '👺', 92],
            ['Banaspati', 'Bola api terbang yang panas membara, cocok buat nemenin camping biar nggak kedinginan.', 'hantu', '🔥', 90],
            ['Palasik Imut', 'Kepala terbang cari mangsa, tapi sering nyangkut di tiang listrik.', 'hantu', '🦇', 75],
            ['Kuyang Skincare', 'Sering terbang malam buat nyari diskonan serum anti-aging.', 'hantu', '🧛‍♀️', 78],
            ['Jelangkung Bete', 'Datang tak diundang, eh pas mau pulang minta ongkos Grab.', 'hantu', '🎎', 65],
            ['Wewe Gombel TikTok', 'Suka ngumpetin anak kecil sambil ngajak FYP joget-joget.', 'hantu', '🧟‍♀️', 80],
            ['Sundel Bolong Gaul', 'Punggungnya bolong, tapi ditutupin stiker Supreme.', 'hantu', '🧛‍♀️', 85],
            ['Kolong Wewe', 'Bersembunyi di bawah meja, menunggu kerupuk jatuh.', 'hantu', '👹', 60],
            ['Jin Ifrit', 'Khodam kuno dari timur tengah, kuat banget tapi sering salah paham bahasa Indonesia.', 'hantu', '🧞‍♂️', 99],
            ['Si Manis Jembatan Ancol', 'Pesona tak tertandingi, bikin buaya darat auto taubat.', 'hantu', '🧚‍♀️', 96],
            ['Setan Kredit', 'Muncul setiap tanggal 25, auranya bikin kamu langsung kepikiran cicilan.', 'hantu', '💳', 88],
            ['Pocong Merah', 'Lebih galak dari pocong putih, karena habis mandi sambal balado.', 'hantu', '🌶️', 89],
            ['Kuntilanak Galau', 'Nggak suka nakutin orang, lebih suka dengerin lagu sedih di pojokan.', 'hantu', '🎧', 50],
            ['Genderuwo Cinta Damai', 'Bentuk sangar, tapi hatinya hello kitty. Suka nanem bunga.', 'hantu', '🌻', 75],
            ['Tuyul Magang', 'Masih amatir, sering salah nyolong malah ambil kembalian permen.', 'hantu', '🍬', 40],
            ['Babi Ngepet Diet', 'Gagal nyolong karena terjebak di pagar, sekarang rajin zumba.', 'hantu', '🐽', 60],
            ['Hantu Muka Rata', 'Mukanya nggak ada, jadi hemat biaya skincare tiap bulan.', 'hantu', '😶', 75],
            ['Suster Keramas', 'Selalu bawa sampo sachet kemana-mana, wangi tapi mistis.', 'hantu', '🚿', 70],
            ['Kakek Cangkul', 'Cari kerjaan jadi tukang kebun tapi bayarannya doa.', 'hantu', '⛏️', 65],
            ['Leak Bali', 'Sihir kuno yang mematikan, auranya penuh misteri dan magis.', 'hantu', '👹', 95],
            ['Anjing Tanah', 'Khodam penjaga gaib bawah tanah, sangat protektif sama tuannya.', 'hewan', '🐕', 80],
            ['Siluman Harimau', 'Wibawa luar biasa, satu kali mengaum semua cicilan lunas.', 'hewan', '🐯', 98],
            ['Begu Ganjang', 'Makhluk tinggi panjang dari tanah Batak. Bikin musuhmu ngeri.', 'hantu', '👻', 92],
            ['Hantu Jeruk Purut', 'Suka jalan-jalan nyari kopi pait tengah malam.', 'hantu', '🌳', 77],
            ['Ompong', 'Setan iseng yang suka nyembunyiin remot TV saat lagi seru-serunya.', 'hantu', '📺', 50],
            ['Jin Qorin', 'Paling tahu aib-aibmu, karena dia yang selalu nemenin dari lahir.', 'hantu', '👯', 90],
            ['Siluman Buaya Putih', 'Ganteng/Cantik maksimal, auranya bikin orang mabuk kepayang.', 'hantu', '🐊', 95],
            ['Naga Puspa', 'Membawa kejayaan dan rezeki dari arah yang tak disangka.', 'hewan', '🐉', 99],
            ['Macan Kumbang', 'Bergerak dalam bayangan, sangat lincah dan tak kasat mata.', 'hewan', '🐆', 93],
            ['Garuda Hitam', 'Aura misterius yang melindungi dari kiriman ilmu hitam.', 'hewan', '🦅', 96],
            ['Keris Berdiri', 'Bukan makhluk, tapi benda bertuah yang bikin wibawamu naik 100x lipat.', 'benda', '🗡️', 85],
            ['Tuyul Kripto', 'Nggak butuh lilin, mainannya udah trading Bitcoin.', 'hantu', '📈', 97],
            ['Kuntilanak K-Pop', 'Nangis bukan karena sedih, tapi karena bias-nya wajib militer.', 'hantu', '🎤', 65],
            ['Pocong TikTok', 'Lompat-lompatnya udah disesuaikan sama beat jedag-jedug.', 'hantu', '🎵', 75],
            ['Genderuwo Introvert', 'Nggak suka ketemu manusia, lebih milih rebahan di pohon beringin.', 'hantu', '🌳', 60],
            ['Wewe Gombel Sosialita', 'Selalu pakai tas branded hasil culik anak konglomerat.', 'hantu', '👜', 82],
            ['Suster Ngesot Drift', 'Bisa belok patah di tikungan lorong dengan kecepatan tinggi.', 'hantu', '🏎️', 88],
            ['Babi Ngepet Crypto', 'Nyolongnya pakai WiFi, aman dari pukulan warga.', 'hantu', '💻', 94],
            ['Kolor Ijo', 'Sudah pensiun, sekarang buka usaha laundry kiloan.', 'hantu', '🩳', 68],
            ['Siluman Monyet', 'Pandai cari celah dan peluang, otak bisnisnya jalan banget.', 'hewan', '🐒', 85],
            ['Macan Kemayoran', 'Sangat loyal dan protektif terhadap wilayah kekuasaannya.', 'hewan', '🐅', 90],
            ['Kuyang Modis', 'Urat dan organ dalamnya tertata rapi sesuai fengshui.', 'hantu', '✨', 76],
            ['Jelangkung Pro Player', 'Sekali dipanggil langsung penta-kill di rank.', 'hantu', '🎮', 80],
            ['Hantu Air', 'Suka iseng narik kaki orang yang lagi berenang, padahal cuma mau ngajak main.', 'hantu', '🌊', 70],
            ['Gundul Pringis', 'Kepala botak yang hobi nyengir, bikin kaget tapi sebenarnya ramah.', 'hantu', '😬', 65],
            ['Setan Payung', 'Muncul kalau hujan deras buat nawarin jasa ojek payung gaib.', 'hantu', '☂️', 55],
            ['Kucing Hitam Peka', 'Mata ketiganya aktif, selalu meong kalau ada bahaya datang.', 'hewan', '🐈‍⬛', 84],
            ['Ular Phyton Gaib', 'Militan banget, kalau udah nempel susah dilepas.', 'hewan', '🐍', 88],
            ['Burung Gagak', 'Pembawa pesan dari dimensi lain, instingnya sangat kuat.', 'hewan', '🐦‍⬛', 86],
            ['Banteng Merah', 'Aura sangat bersemangat, pantang mundur sebelum menang.', 'hewan', '🐂', 95],
            ['Nyi Blorong', 'Membawa kekayaan luar biasa, tapi ingat pesan moral: jangan serakah.', 'hantu', '🐍', 98],
            ['Jin Botol', 'Penuhi 3 permintaanmu, asalkan permintaannya nggak aneh-aneh.', 'hantu', '🏺', 92],
            ['Siluman Serigala', 'Loyal ke satu majikan, auranya sangat garang.', 'hewan', '🐺', 89],
            ['Pocong Mumun', 'Matanya ijo, paling terkenal di zamannya. Legenda TV!', 'hantu', '👀', 90],
            ['Kuntilanak Ngesot', 'Lagi capek terbang, jadi minjem gayanya suster.', 'hantu', '👻', 60],
            ['Genderuwo Bucin', 'Kalau udah suka sama orang, bakal ditungguin sampai kapanpun.', 'hantu', '💞', 75],
            ['Tuyul Pensiun', 'Udah capek nyolong, sekarang fokus jualan token listrik.', 'hantu', '⚡', 50],
            ['Hantu Bangku Kosong', 'Selalu nemenin kamu duduk biar nggak kelihatan jomblo amat.', 'hantu', '🪑', 40],
            ['Setan Valak', 'Kelihatan serem, aslinya bingung jalan pulang ke Rumania.', 'hantu', '🧛‍♀️', 85],
            ['Hantu Casablanka', 'Suka nongkrong di terowongan nyari tumpangan gratis.', 'hantu', '🚗', 75],
            ['Jenglot', 'Kecil-kecil cabe rawit, energinya padat dan mistis.', 'hantu', '🧛‍♂️', 88],
            ['Mustika Merah Delima', 'Khodam berbentuk batu sakti, bikin aura wajahmu bersinar.', 'benda', '🔴', 96],
            ['Batu Akik', 'Menambah kewibawaan ala bapak-bapak di pos ronda.', 'benda', '💍', 70],
            ['Bambu Petuk', 'Rezeki mengalir deras dari dua arah yang berbeda.', 'benda', '🎋', 94],
            ['Siluman Singa', 'Wibawa raja hutan, semua bawahan auto nurut.', 'hewan', '🦁', 92],
            ['Macan Loreng', 'Aura petarung sejati, nggak pernah lari dari masalah.', 'hewan', '🐅', 90],
            ['Kuda Lumping', 'Bisa makan beling (metafora), artinya mentalmu baja.', 'hewan', '🐎', 85],
            ['Siluman Kera Putih', 'Suci dan bijaksana, selalu ngasih ide cemerlang.', 'hewan', '🐒', 91],
            ['Kucing Belang Tiga', 'Membawa hoki besar bagi yang merawatnya.', 'hewan', '🐈', 89],
            ['Burung Perkutut', 'Sangat priyayi, auranya menenangkan dan damai.', 'hewan', '🕊️', 75],
            ['Ayam Cemani', 'Eksotis dan mahal, melambangkan keistimewaan tingkat tinggi.', 'hewan', '🐓', 86],
            ['Ikan Mas Koki', 'Bikin rumah selalu terasa adem dan banyak rezeki.', 'hewan', '🐡', 70],
            ['Kelelawar Emas', 'Membawa kekayaan di saat orang lain tertidur lelap.', 'hewan', '🦇', 88],
            ['Laba-laba Gaib', 'Pandai merajut jaring rezeki dan koneksi bisnis.', 'hewan', '🕷️', 82],
            ['Pocong Neon', 'Bisa nyala dalam gelap, jadi gampang dicari kalau mati lampu.', 'hantu', '💡', 80],
            ['Kuntilanak Glow in the dark', 'Skincare-nya mengandung fosfor, nyala hijau kalau malam.', 'hantu', '✨', 85],
            ['Genderuwo Vegetarian', 'Badan gede tapi cuma makan bayam, sangat sehat.', 'hantu', '🥗', 70],
            ['Tuyul Jujur', 'Kalau nemu uang di jalan diserahin ke pos polisi.', 'hantu', '👮', 60],
            ['Babi Ngepet Syariah', 'Investasinya selalu di sektor riil dan halal.', 'hantu', '🕋', 95],
            ['Wewe Gombel Nanny', 'Buka jasa penitipan anak profesional tanpa biaya tambahan.', 'hantu', '👶', 85],
            ['Suster Ngesot Atlet', 'Udah ikut olimpiade cabang lari ngesot 100m.', 'hantu', '🏅', 90],
            ['Palasik Vegan', 'Sekarang cuma mau nyedot sari buah apel.', 'hantu', '🍎', 65],
            ['Buto Ijo Diet', 'Badannya udah ideal, rajin nge-gym tiap subuh.', 'hantu', '💪', 88],
            ['Kuyang Hijab', 'Tetap menutup aurat meski kepala doang yang terbang.', 'hantu', '🧕', 80],
            ['Jelangkung Selebgram', 'Sekali dipanggil langsung minta difoto buat endorse.', 'hantu', '📸', 75],
            ['Setan Kredit Macet', 'Selalu datang kalau tanggal tua buat ngingetin utang.', 'hantu', '💸', 82],
            ['Hantu Skripsi', 'Selalu menghantui mahasiswa tingkat akhir yang males ngetik.', 'hantu', '📚', 99],
            ['Pocong Mandiri', 'Bisa buka ikatan talinya sendiri kalau mau makan.', 'hantu', '🎀', 70],
            ['Kuntilanak Sopan', 'Kalau mau ketawa permisi dulu biar nggak ngagetin.', 'hantu', '🙏', 75],
            ['Genderuwo Barber', 'Bulunya rapi banget karena sering ke barbershop.', 'hantu', '✂️', 80],
            ['Tuyul Gamer', 'Uangnya habis buat top up diamond Free Fire.', 'hantu', '💎', 50],
            ['Babi Ngepet Santuy', 'Nyalain lilinnya pakai korek elektrik biar nggak gampang mati.', 'hantu', '🔥', 85],
            ['Wewe Gombel Kesepian', 'Butuh teman ngobrol, auranya melankolis.', 'hantu', '😢', 60],
            ['Suster Ngesot Spa', 'Jalannya lambat karena sekalian luluran di lantai.', 'hantu', '💆‍♀️', 72],
            ['Khodam Netizen', 'Maha Benar dengan segala komentarnya. Bikin musuh kena mental.', 'benda', '📱', 100],
        ];

        $data = [];
        foreach ($templates as $item) {
            $data[] = [
                'name' => $item[0],
                'description' => $item[1],
                'type' => $item[2],
                'emoji' => $item[3],
                'power_level' => $item[4],
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        KhodamTemplate::insert($data);
    }
}
